### PR TITLE
Upgrade resty dependency

### PR DESCRIPTION
**Pull request by mauricioabreu**
Update imports
Update logger interface
Fix tests

### CODE REVIEW

**Comment by KalilCazes** [comment]
Awesome work ❤️ .

**Review by KalilCazes — APPROVED** [review]

**Comment by lucasrodcosta** [comment]
@mauricioabreu why change the logger interface?

It wouldn't be enough to keep the `NewHTTPClient` receiving an `io.Writer` instead of a `Logger`?

**Comment by mauricioabreu** [comment]
@lucasrodcosta I had to change the interface because resty got upgraded, and the new interface is different from v1 

One thing I have noticed is that they created a interface for this. So we can replace our custom interface by `resty.Logger`. What is your opinion?

**Comment by mauricioabreu** [comment]
I've changed the custom interface by `resty.Logger` @lucasrodcosta @KalilCazes

**Review by lucasrodcosta — APPROVED** [review]

**Comment by KalilCazes** [comment]
Hey @mauricioabreu . 

Could you update the _examples_ section in README? After this PR, a logger struct is needed to initialize `NewHTTPClient()`

**Comment by mauricioabreu** [comment]
Good gatch @KalilCazes 

Done!

**Review by dneto — APPROVED** [review]

**Pull request merged**
